/* SPDX-License-Identifier: BSD-3-Clause */
/* Static raw PDO enumeration for the functions integrated in a Time Card. */

#include "timecard.h"

/* {B5415088-5EE1-4D3A-8519-C3487370E0BF} */
const GUID GUID_DEVCLASS_TIMECARD =
    { 0xb5415088, 0x5ee1, 0x4d3a,
      { 0x85, 0x19, 0xc3, 0x48, 0x73, 0x70, 0xe0, 0xbf } };

typedef struct _TIMECARD_CHILD_DESCRIPTION {
    TIMECARD_SUBSYSTEM Subsystem;
    PCWSTR DeviceId;
    PCWSTR InstanceId;
    PCWSTR Description;
} TIMECARD_CHILD_DESCRIPTION;

static const TIMECARD_CHILD_DESCRIPTION TimeCardChildren[] = {
    { TimeCardSubsystemPhc, L"TIMECARD\\PHC", L"PHC",
      L"Time Card Precision Hardware Clock (PHC)" },
    { TimeCardSubsystemTod, L"TIMECARD\\TOD", L"TOD",
      L"Time Card GNSS Time-of-Day Engine" },
    { TimeCardSubsystemGnss, L"TIMECARD\\UART_GNSS", L"UART_GNSS",
      L"Time Card GNSS Receiver (UART)" },
    { TimeCardSubsystemGnss2, L"TIMECARD\\UART_GNSS2", L"UART_GNSS2",
      L"Time Card Secondary GNSS Receiver (UART)" },
    { TimeCardSubsystemAtomicClock, L"TIMECARD\\UART_MAC", L"UART_MAC",
      L"Time Card Atomic Clock (UART)" },
    { TimeCardSubsystemNmea, L"TIMECARD\\UART_NMEA", L"UART_NMEA",
      L"Time Card NMEA Output (UART)" },
    { TimeCardSubsystemSma, L"TIMECARD\\SMA", L"SMA",
      L"Time Card SMA Inputs and Outputs" },
    { TimeCardSubsystemTimingIo, L"TIMECARD\\TIMING_IO", L"TIMING_IO",
      L"Time Card Timestamp and Signal Generators" },
    { TimeCardSubsystemI2c, L"TIMECARD\\I2C", L"I2C",
      L"Time Card I2C Controller" },
    { TimeCardSubsystemFlash, L"TIMECARD\\FLASH", L"FLASH",
      L"Time Card FPGA Firmware and SPI Flash" },
    { TimeCardSubsystemPtm, L"TIMECARD\\PTM", L"PTM",
      L"Time Card PCIe Precision Time Measurement (PTM)" }
};

C_ASSERT(ARRAYSIZE(TimeCardChildren) == TIMECARD_SUBSYSTEM_COUNT);

static NTSTATUS
TimeCardCreateChild(WDFDEVICE parent,
                    const TIMECARD_CHILD_DESCRIPTION *description,
                    WDFDEVICE *childDevice)
{
    DECLARE_CONST_UNICODE_STRING(location, L"on OCP Time Card");
    DECLARE_CONST_UNICODE_STRING(sddl,
        L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");
    WDF_OBJECT_ATTRIBUTES attributes;
    PTIMECARD_CHILD_CONTEXT context;
    UNICODE_STRING deviceId;
    UNICODE_STRING instanceId;
    UNICODE_STRING deviceText;
    PWDFDEVICE_INIT childInit;
    WDFDEVICE child;
    NTSTATUS status;

    childInit = WdfPdoInitAllocate(parent);
    if (childInit == NULL)
        return STATUS_INSUFFICIENT_RESOURCES;

    WdfDeviceInitSetDeviceType(childInit, FILE_DEVICE_UNKNOWN);
    WdfDeviceInitSetIoType(childInit, WdfDeviceIoBuffered);
    /*
     * A secured framework device must have a name. Let the I/O manager name
     * each raw PDO before WdfDeviceInitAssignSDDLString applies its ACL.
     */
    WdfDeviceInitSetCharacteristics(
        childInit,
        FILE_AUTOGENERATED_DEVICE_NAME | FILE_DEVICE_SECURE_OPEN,
        FALSE);

    status = WdfPdoInitAssignRawDevice(childInit, &GUID_DEVCLASS_TIMECARD);
    if (!NT_SUCCESS(status))
        goto FailInit;

    /*
     * Raw PDOs have no function driver from which to inherit a security
     * descriptor. Assign one explicitly, as required by the KMDF raw-PDO
     * model. Omitting this makes WdfDeviceCreate fail with
     * STATUS_INVALID_SECURITY_DESCR on current Windows builds.
     */
    status = WdfDeviceInitAssignSDDLString(childInit, &sddl);
    if (!NT_SUCCESS(status))
        goto FailInit;

    RtlInitUnicodeString(&deviceId, description->DeviceId);
    status = WdfPdoInitAssignDeviceID(childInit, &deviceId);
    if (!NT_SUCCESS(status))
        goto FailInit;

    status = WdfPdoInitAddHardwareID(childInit, &deviceId);
    if (!NT_SUCCESS(status))
        goto FailInit;

    RtlInitUnicodeString(&instanceId, description->InstanceId);
    status = WdfPdoInitAssignInstanceID(childInit, &instanceId);
    if (!NT_SUCCESS(status))
        goto FailInit;

    RtlInitUnicodeString(&deviceText, description->Description);
    status = WdfPdoInitAddDeviceText(childInit, &deviceText, &location,
                                     0x0409);
    if (!NT_SUCCESS(status))
        goto FailInit;
    WdfPdoInitSetDefaultLocale(childInit, 0x0409);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes,
                                             TIMECARD_CHILD_CONTEXT);
    status = WdfDeviceCreate(&childInit, &attributes, &child);
    if (!NT_SUCCESS(status))
        return status;

    context = TimeCardChildGetContext(child);
    context->Subsystem = description->Subsystem;

    status = WdfFdoAddStaticChild(parent, child);
    if (!NT_SUCCESS(status)) {
        WdfObjectDelete(child);
    } else {
        *childDevice = child;
    }
    return status;

FailInit:
    WdfDeviceInitFree(childInit);
    return status;
}

NTSTATUS
TimeCardCreateSubsystemDevices(PDEVICE_CONTEXT context)
{
    ULONG i;
    NTSTATUS status;

    if (context->HierarchyCreated)
        return STATUS_SUCCESS;

    for (i = 0; i < ARRAYSIZE(TimeCardChildren); ++i) {
        if ((context->SubsystemMask &
             TIMECARD_SUBSYSTEM_BIT(TimeCardChildren[i].Subsystem)) == 0) {
            continue;
        }
        if (context->ChildDevices[i] != NULL)
            continue;
        status = TimeCardCreateChild(context->Device, &TimeCardChildren[i],
                                     &context->ChildDevices[i]);
        if (!NT_SUCCESS(status)) {
            KdPrint(("timecard: failed to create child %lu, status 0x%08lx\n",
                     i, status));
            return status;
        }
    }
    context->HierarchyCreated = TRUE;
    return STATUS_SUCCESS;
}

static NTSTATUS
TimeCardOpenDeviceRegistry(PDEVICE_CONTEXT context, ACCESS_MASK access,
                           WDFKEY *key)
{
    return WdfDeviceOpenRegistryKey(context->Device, PLUGPLAY_REGKEY_DEVICE,
                                    access, WDF_NO_OBJECT_ATTRIBUTES, key);
}

NTSTATUS
TimeCardGetHierarchySetting(PDEVICE_CONTEXT context, PBOOLEAN enabled)
{
    DECLARE_CONST_UNICODE_STRING(valueName, L"EnableSubsystemDevices");
    ULONG value = 0;
    WDFKEY key;
    NTSTATUS status;

    /*
     * A supported Time Card should expose its functional children on first
     * installation.  Keep the registry value as an administrator override,
     * but treat an absent value as enabled so a newly encountered board
     * variant does not appear as only the parent PCI controller.
     */
    *enabled = TRUE;
    status = TimeCardOpenDeviceRegistry(context, KEY_QUERY_VALUE, &key);
    if (!NT_SUCCESS(status))
        return status;

    status = WdfRegistryQueryULong(key, &valueName, &value);
    WdfRegistryClose(key);
    if (status == STATUS_OBJECT_NAME_NOT_FOUND ||
        status == STATUS_OBJECT_PATH_NOT_FOUND) {
        return STATUS_SUCCESS;
    }
    if (NT_SUCCESS(status))
        *enabled = value != 0;
    return status;
}

static NTSTATUS
TimeCardSetHierarchySetting(PDEVICE_CONTEXT context, BOOLEAN enabled)
{
    DECLARE_CONST_UNICODE_STRING(valueName, L"EnableSubsystemDevices");
    WDFKEY key;
    NTSTATUS status;

    status = TimeCardOpenDeviceRegistry(context, KEY_SET_VALUE, &key);
    if (!NT_SUCCESS(status))
        return status;
    status = WdfRegistryAssignULong(key, &valueName, enabled ? 1u : 0u);
    WdfRegistryClose(key);
    return status;
}

NTSTATUS
TimeCardControlHierarchy(PDEVICE_CONTEXT context,
                         const TIMECARD_HIERARCHY_CONTROL *request,
                         TIMECARD_HIERARCHY_CONTROL *response)
{
    BOOLEAN persisted = FALSE;
    NTSTATUS status = STATUS_SUCCESS;

    if (request->Size != sizeof(*request) ||
        request->Action > TIMECARD_HIERARCHY_DISABLE ||
        request->Persist > 1u) {
        return STATUS_INVALID_PARAMETER;
    }

    if (request->Action == TIMECARD_HIERARCHY_ENABLE) {
        status = TimeCardCreateSubsystemDevices(context);
        if (NT_SUCCESS(status) && request->Persist != 0)
            status = TimeCardSetHierarchySetting(context, TRUE);
    } else if (request->Action == TIMECARD_HIERARCHY_DISABLE &&
               request->Persist != 0) {
        /* Existing children remain until the parent device is restarted. */
        status = TimeCardSetHierarchySetting(context, FALSE);
    }
    if (!NT_SUCCESS(status))
        return status;

    status = TimeCardGetHierarchySetting(context, &persisted);
    if (!NT_SUCCESS(status))
        return status;

    RtlZeroMemory(response, sizeof(*response));
    response->Size = sizeof(*response);
    response->Action = request->Action;
    response->Persist = request->Persist;
    response->RuntimeEnabled = context->HierarchyCreated ? 1u : 0u;
    response->Persisted = persisted ? 1u : 0u;
    return STATUS_SUCCESS;
}
